// This file is auto-generated by @hey-api/openapi-ts

export const AuditActionSchema = {
    type: 'string',
    enum: ['spec_change_request', 'spec_change_apply', 'snapshot_create', 'snapshot_delete', 'snapshot_rollback', 'config_update', 'vm_create', 'lxc_create', 'resource_start', 'resource_stop', 'resource_reboot', 'resource_shutdown', 'resource_reset', 'resource_delete', 'vm_request_submit', 'vm_request_review', 'user_create', 'user_update', 'user_delete'],
    title: 'AuditAction',
    description: '審計操作類型'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        },
        vmid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vmid'
        },
        action: {
            '$ref': '#/components/schemas/AuditAction'
        },
        details: {
            type: 'string',
            title: 'Details'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        user_agent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Agent'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'vmid', 'action', 'details', 'ip_address', 'user_agent', 'created_at'],
    title: 'AuditLogPublic',
    description: '公開的審計日誌資訊'
} as const;

export const AuditLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditLogsPublic',
    description: '審計日誌列表'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CurrentStatsResponseSchema = {
    properties: {
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu',
            description: 'CPU 使用率 (0-1)'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu',
            description: 'CPU 核心數'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem',
            description: '當前記憶體使用 (bytes)'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem',
            description: '最大記憶體 (bytes)'
        },
        disk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk',
            description: '當前磁碟使用 (bytes)'
        },
        maxdisk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdisk',
            description: '最大磁碟 (bytes)'
        },
        netin: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netin',
            description: '網絡輸入 (bytes)'
        },
        netout: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netout',
            description: '網絡輸出 (bytes)'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime',
            description: '運行時間 (seconds)'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: '狀態 (running, stopped, etc.)'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'CurrentStatsResponse',
    description: '當前實時狀態'
} as const;

export const DirectSpecUpdateRequestSchema = {
    properties: {
        cores: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 32,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cores',
            description: 'CPU 核心數'
        },
        memory: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65536,
                    minimum: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory',
            description: '記憶體 (MB)'
        },
        disk_size: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk Size',
            description: '磁碟大小增量 (例如 "+10G"，僅能增加)'
        }
    },
    type: 'object',
    title: 'DirectSpecUpdateRequest',
    description: '管理員直接調整規格'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LXCCreateResponseSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        upid: {
            type: 'string',
            title: 'Upid'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'upid', 'message'],
    title: 'LXCCreateResponse',
    description: 'Response after creating LXC container.'
} as const;

export const LXCCreateSchemaSchema = {
    properties: {
        hostname: {
            type: 'string',
            title: 'Hostname'
        },
        ostemplate: {
            type: 'string',
            title: 'Ostemplate'
        },
        cores: {
            type: 'integer',
            title: 'Cores',
            default: 1
        },
        memory: {
            type: 'integer',
            title: 'Memory',
            default: 512
        },
        rootfs_size: {
            type: 'integer',
            title: 'Rootfs Size',
            default: 8
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        storage: {
            type: 'string',
            title: 'Storage',
            default: 'local-lvm'
        },
        environment_type: {
            type: 'string',
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        start: {
            type: 'boolean',
            title: 'Start',
            default: true
        },
        unprivileged: {
            type: 'boolean',
            title: 'Unprivileged',
            default: true
        }
    },
    type: 'object',
    required: ['hostname', 'ostemplate', 'password', 'environment_type'],
    title: 'LXCCreateSchema',
    description: 'Schema for creating a new LXC container.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: '通用訊息回應'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: '重設密碼請求'
} as const;

export const NodeSchemaSchema = {
    properties: {
        node: {
            type: 'string',
            title: 'Node'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime'
        }
    },
    type: 'object',
    required: ['node', 'status'],
    title: 'NodeSchema',
    description: 'Proxmox node information.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RRDDataPointSchema = {
    properties: {
        time: {
            type: 'integer',
            title: 'Time',
            description: '時間戳'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        disk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk'
        },
        maxdisk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdisk'
        },
        netin: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netin'
        },
        netout: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netout'
        }
    },
    type: 'object',
    required: ['time'],
    title: 'RRDDataPoint',
    description: 'RRD 數據點'
} as const;

export const RRDDataResponseSchema = {
    properties: {
        timeframe: {
            type: 'string',
            title: 'Timeframe',
            description: '時間範圍'
        },
        data: {
            items: {
                '$ref': '#/components/schemas/RRDDataPoint'
            },
            type: 'array',
            title: 'Data',
            description: '數據點列表'
        }
    },
    type: 'object',
    required: ['timeframe', 'data'],
    title: 'RRDDataResponse',
    description: 'RRD 歷史數據響應'
} as const;

export const ResourcePublicSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        node: {
            type: 'string',
            title: 'Node'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        environment_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime'
        }
    },
    type: 'object',
    required: ['vmid', 'name', 'status', 'node', 'type'],
    title: 'ResourcePublic',
    description: '公開的資源資訊，合併Proxmox資料和資料庫額外資訊.'
} as const;

export const SnapshotCreateRequestSchema = {
    properties: {
        snapname: {
            type: 'string',
            maxLength: 40,
            minLength: 1,
            title: 'Snapname',
            description: '快照名稱'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: '快照描述'
        },
        vmstate: {
            type: 'boolean',
            title: 'Vmstate',
            description: '是否包含 RAM 狀態 (僅 VM)',
            default: false
        }
    },
    type: 'object',
    required: ['snapname'],
    title: 'SnapshotCreateRequest',
    description: '創建快照請求'
} as const;

export const SnapshotInfoSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: '快照名稱'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: '快照描述'
        },
        snaptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Snaptime',
            description: '創建時間戳'
        },
        vmstate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vmstate',
            description: '是否包含 VM 狀態 (0/1)'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SnapshotInfo',
    description: '快照信息'
} as const;

export const SnapshotResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        task_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Id'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'SnapshotResponse',
    description: '快照操作響應'
} as const;

export const SpecChangeRequestCreateSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        change_type: {
            '$ref': '#/components/schemas/SpecChangeType'
        },
        reason: {
            type: 'string',
            minLength: 10,
            title: 'Reason',
            description: '調整原因至少10字'
        },
        requested_cpu: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 32,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Cpu'
        },
        requested_memory: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65536,
                    minimum: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Memory'
        },
        requested_disk: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Disk'
        }
    },
    type: 'object',
    required: ['vmid', 'change_type', 'reason'],
    title: 'SpecChangeRequestCreate',
    description: '創建規格調整申請'
} as const;

export const SpecChangeRequestPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        },
        change_type: {
            '$ref': '#/components/schemas/SpecChangeType'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        current_cpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Cpu'
        },
        current_memory: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Memory'
        },
        current_disk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Disk'
        },
        requested_cpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Cpu'
        },
        requested_memory: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Memory'
        },
        requested_disk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested Disk'
        },
        status: {
            '$ref': '#/components/schemas/SpecChangeRequestStatus'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        review_comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Comment'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        },
        applied_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Applied At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'vmid', 'user_id', 'change_type', 'reason', 'current_cpu', 'current_memory', 'current_disk', 'requested_cpu', 'requested_memory', 'requested_disk', 'status', 'reviewer_id', 'review_comment', 'reviewed_at', 'applied_at', 'created_at'],
    title: 'SpecChangeRequestPublic',
    description: '公開的規格調整申請資訊'
} as const;

export const SpecChangeRequestReviewSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/SpecChangeRequestStatus'
        },
        review_comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Comment'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'SpecChangeRequestReview',
    description: '審核規格調整申請'
} as const;

export const SpecChangeRequestStatusSchema = {
    type: 'string',
    enum: ['pending', 'approved', 'rejected'],
    title: 'SpecChangeRequestStatus',
    description: '規格調整申請狀態'
} as const;

export const SpecChangeRequestsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SpecChangeRequestPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SpecChangeRequestsPublic',
    description: '規格調整申請列表'
} as const;

export const SpecChangeTypeSchema = {
    type: 'string',
    enum: ['cpu', 'memory', 'disk', 'combined'],
    title: 'SpecChangeType',
    description: '規格調整類型'
} as const;

export const TemplateSchemaSchema = {
    properties: {
        volid: {
            type: 'string',
            title: 'Volid'
        },
        format: {
            type: 'string',
            title: 'Format'
        },
        size: {
            type: 'integer',
            title: 'Size'
        }
    },
    type: 'object',
    required: ['volid', 'format', 'size'],
    title: 'TemplateSchema',
    description: 'OS template information.'
} as const;

export const TerminalInfoSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        ws_url: {
            type: 'string',
            title: 'Ws Url'
        },
        ticket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'ws_url', 'message'],
    title: 'TerminalInfoSchema',
    description: 'Terminal console connection information for LXC containers.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JWT 存取權杖回應'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: '更新密碼請求'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: '建立使用者時接收的資料'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'API 回傳的使用者資料'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: '使用者自行註冊時使用的資料'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: '更新使用者時接收的資料'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: '使用者更新自己資料時使用'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'API 回傳的使用者列表'
} as const;

export const VMCreateResponseSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        upid: {
            type: 'string',
            title: 'Upid'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'upid', 'message'],
    title: 'VMCreateResponse',
    description: 'Response after creating VM.'
} as const;

export const VMCreateSchemaSchema = {
    properties: {
        hostname: {
            type: 'string',
            title: 'Hostname'
        },
        template_id: {
            type: 'integer',
            title: 'Template Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        cores: {
            type: 'integer',
            title: 'Cores',
            default: 2
        },
        memory: {
            type: 'integer',
            title: 'Memory',
            default: 2048
        },
        disk_size: {
            type: 'integer',
            title: 'Disk Size',
            default: 20
        },
        storage: {
            type: 'string',
            title: 'Storage',
            default: 'local-lvm'
        },
        environment_type: {
            type: 'string',
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        start: {
            type: 'boolean',
            title: 'Start',
            default: true
        }
    },
    type: 'object',
    required: ['hostname', 'template_id', 'username', 'password', 'environment_type'],
    title: 'VMCreateSchema',
    description: 'Schema for creating a new VM from cloud-init template.'
} as const;

export const VMRequestCreateSchema = {
    properties: {
        reason: {
            type: 'string',
            minLength: 10,
            title: 'Reason'
        },
        resource_type: {
            type: 'string',
            title: 'Resource Type'
        },
        hostname: {
            type: 'string',
            maxLength: 63,
            title: 'Hostname'
        },
        cores: {
            type: 'integer',
            title: 'Cores',
            default: 2
        },
        memory: {
            type: 'integer',
            title: 'Memory',
            default: 2048
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        storage: {
            type: 'string',
            title: 'Storage',
            default: 'local-lvm'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        ostemplate: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ostemplate'
        },
        rootfs_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rootfs Size'
        },
        template_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template Id'
        },
        disk_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk Size'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        }
    },
    type: 'object',
    required: ['reason', 'resource_type', 'hostname', 'password'],
    title: 'VMRequestCreate',
    description: '建立虛擬機申請的 Schema.'
} as const;

export const VMRequestPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        resource_type: {
            type: 'string',
            title: 'Resource Type'
        },
        hostname: {
            type: 'string',
            title: 'Hostname'
        },
        cores: {
            type: 'integer',
            title: 'Cores'
        },
        memory: {
            type: 'integer',
            title: 'Memory'
        },
        storage: {
            type: 'string',
            title: 'Storage'
        },
        environment_type: {
            type: 'string',
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        ostemplate: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ostemplate'
        },
        rootfs_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rootfs Size'
        },
        template_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template Id'
        },
        disk_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk Size'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        status: {
            '$ref': '#/components/schemas/VMRequestStatus'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        review_comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Comment'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        },
        vmid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vmid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'reason', 'resource_type', 'hostname', 'cores', 'memory', 'storage', 'environment_type', 'status', 'created_at'],
    title: 'VMRequestPublic',
    description: '公開的虛擬機申請資訊.'
} as const;

export const VMRequestReviewSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/VMRequestStatus'
        },
        review_comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Comment'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'VMRequestReview',
    description: '審核虛擬機申請的 Schema.'
} as const;

export const VMRequestStatusSchema = {
    type: 'string',
    enum: ['pending', 'approved', 'rejected'],
    title: 'VMRequestStatus',
    description: '虛擬機申請狀態'
} as const;

export const VMRequestsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VMRequestPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'VMRequestsPublic',
    description: '虛擬機申請列表.'
} as const;

export const VMSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        node: {
            type: 'string',
            title: 'Node'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime'
        },
        netin: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netin'
        },
        diskread: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diskread'
        },
        diskwrite: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diskwrite'
        },
        disk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk'
        },
        template: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template'
        },
        memhost: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memhost'
        },
        maxdisk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdisk'
        }
    },
    type: 'object',
    required: ['vmid', 'name', 'status', 'node', 'type'],
    title: 'VMSchema',
    description: 'Virtual machine information.'
} as const;

export const VMTemplateSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        node: {
            type: 'string',
            title: 'Node'
        }
    },
    type: 'object',
    required: ['vmid', 'name', 'node'],
    title: 'VMTemplateSchema',
    description: 'VM template information.'
} as const;

export const VNCInfoSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        ws_url: {
            type: 'string',
            title: 'Ws Url'
        },
        ticket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'ws_url', 'message'],
    title: 'VNCInfoSchema',
    description: 'VNC console connection information.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;