// This file is auto-generated by @hey-api/openapi-ts

export type AIAPICredentialPublic = {
    id: string;
    request_id: string;
    base_url: string;
    api_key: string;
    api_key_prefix: string;
    expires_at?: (string | null);
    revoked_at?: (string | null);
    created_at: string;
};

export type AIAPICredentialsPublic = {
    data: Array<AIAPICredentialPublic>;
    count: number;
};

export type AIAPIRequestCreate = {
    purpose: string;
};

export type AIAPIRequestPublic = {
    id: string;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    purpose: string;
    status: AIAPIRequestStatus;
    reviewer_id?: (string | null);
    reviewer_email?: (string | null);
    review_comment?: (string | null);
    reviewed_at?: (string | null);
    created_at: string;
};

export type AIAPIRequestReview = {
    status: AIAPIRequestStatus;
    review_comment?: (string | null);
};

export type AIAPIRequestsPublic = {
    data: Array<AIAPIRequestPublic>;
    count: number;
};

export type AIAPIRequestStatus = 'pending' | 'approved' | 'rejected';

export type AiMetrics = {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
    elapsed_seconds?: number;
    tokens_per_second?: number;
};

/**
 * 審計操作類型
 */
export type AuditAction = 'spec_change_request' | 'spec_change_apply' | 'snapshot_create' | 'snapshot_delete' | 'snapshot_rollback' | 'config_update' | 'vm_create' | 'lxc_create' | 'resource_start' | 'resource_stop' | 'resource_reboot' | 'resource_shutdown' | 'resource_reset' | 'resource_delete' | 'vm_request_submit' | 'vm_request_review' | 'ai_api_request_submit' | 'ai_api_request_review' | 'user_create' | 'user_update' | 'user_delete' | 'group_create' | 'group_delete' | 'group_member_add' | 'group_member_remove' | 'batch_provision_vm' | 'batch_provision_lxc';

/**
 * 公開的審計日誌
 */
export type AuditLogPublic = {
    id: string;
    user_id: (string | null);
    user_email?: (string | null);
    user_full_name?: (string | null);
    vmid: (number | null);
    action: AuditAction;
    details: string;
    ip_address: (string | null);
    user_agent: (string | null);
    created_at: string;
};

/**
 * 審計日誌列表
 */
export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type Body_groups_import_members_from_csv = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_proxmox_config_parse_cert = {
    pem: string;
};

/**
 * 解析憑證 PEM 的結果
 */
export type CertParseResult = {
    valid: boolean;
    fingerprint?: (string | null);
    subject?: (string | null);
    issuer?: (string | null);
    not_before?: (string | null);
    not_after?: (string | null);
    error?: (string | null);
};

export type ChatMessage = {
    /**
     * Role of the message sender, usually 'user' or 'assistant'.
     */
    role: string;
    /**
     * Content of the message.
     */
    content: string;
};

export type ChatRequest = {
    /**
     * List of previous chat messages.
     */
    messages: Array<ChatMessage>;
    top_k?: number;
    device_nodes?: Array<DeviceNode>;
};

export type ChatResponse = {
    /**
     * AI text reply.
     */
    reply: string;
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
    elapsed_seconds?: number;
    tokens_per_second?: number;
};

/**
 * 偵測叢集節點的預覽結果（不儲存）
 */
export type ClusterPreviewResult = {
    success: boolean;
    is_cluster: boolean;
    nodes: Array<ProxmoxNodePublic>;
    error?: (string | null);
};

/**
 * 建立 VM 間連線（或 VM 到網關，或 Internet 入站）
 */
export type ConnectionCreate = {
    /**
     * 來源 VM ID；None 代表網關（Internet 入站）
     */
    source_vmid: (number | null);
    /**
     * 目標 VM ID；None 代表網關（上網）
     */
    target_vmid?: (number | null);
    /**
     * 允許通過的端口列表
     */
    ports: Array<PortSpec>;
    /**
     * 連線方向：one_way（單向）或 bidirectional（雙向）
     */
    direction?: 'one_way' | 'bidirectional';
};

/**
 * 連線方向：one_way（單向）或 bidirectional（雙向）
 */
export type direction = 'one_way' | 'bidirectional';

/**
 * 刪除 VM 間連線
 */
export type ConnectionDelete = {
    /**
     * 來源 VM ID；None 代表網關
     */
    source_vmid: (number | null);
    /**
     * 目標 VM ID；None 代表網關
     */
    target_vmid?: (number | null);
    /**
     * 要刪除的端口；None 代表刪除全部連線
     */
    ports?: (Array<PortSpec> | null);
};

/**
 * CSV 大量匯入結果
 */
export type CsvImportResult = {
    created?: Array<(string)>;
    already_existed?: Array<(string)>;
    added_to_group?: number;
    errors?: Array<(string)>;
};

/**
 * 資源即時狀態
 */
export type CurrentStatsResponse = {
    /**
     * CPU usage (0-1)
     */
    cpu?: (number | null);
    /**
     * CPU cores
     */
    maxcpu?: (number | null);
    /**
     * Memory usage (bytes)
     */
    mem?: (number | null);
    /**
     * Max memory (bytes)
     */
    maxmem?: (number | null);
    /**
     * Disk usage (bytes)
     */
    disk?: (number | null);
    /**
     * Max disk (bytes)
     */
    maxdisk?: (number | null);
    /**
     * Network in (bytes)
     */
    netin?: (number | null);
    /**
     * Network out (bytes)
     */
    netout?: (number | null);
    /**
     * Uptime (seconds)
     */
    uptime?: (number | null);
    /**
     * Status
     */
    status: string;
};

export type DeviceNode = {
    node: string;
    maxcpu?: number;
    cpu_usage_ratio?: number;
    maxmem_gb?: number;
    mem_usage_ratio?: number;
    gpu_count?: number;
};

/**
 * 管理員直接調整規格
 */
export type DirectSpecUpdateRequest = {
    /**
     * CPU cores
     */
    cores?: (number | null);
    /**
     * Memory (MB)
     */
    memory?: (number | null);
    /**
     * Disk size increment (e.g. "+10G")
     */
    disk_size?: (string | null);
};

/**
 * 防火牆選項（回應）
 */
export type FirewallOptionsPublic = {
    enable: boolean;
    policy_in: string;
    policy_out: string;
};

/**
 * 建立防火牆規則（原始 Proxmox 規則）
 */
export type FirewallRuleCreate = {
    /**
     * 規則方向
     */
    type: 'in' | 'out';
    /**
     * 動作
     */
    action: 'ACCEPT' | 'DROP' | 'REJECT';
    /**
     * 來源 IP/CIDR
     */
    source?: (string | null);
    /**
     * 目標 IP/CIDR
     */
    dest?: (string | null);
    /**
     * 協定 (tcp/udp/icmp)
     */
    proto?: (string | null);
    /**
     * 目標端口或範圍
     */
    dport?: (string | null);
    /**
     * 來源端口或範圍
     */
    sport?: (string | null);
    /**
     * 是否啟用 (1=是, 0=否)
     */
    enable?: number;
    /**
     * 備註
     */
    comment?: (string | null);
};

/**
 * 規則方向
 */
export type type = 'in' | 'out';

/**
 * 動作
 */
export type action = 'ACCEPT' | 'DROP' | 'REJECT';

/**
 * 防火牆規則（回應）
 */
export type FirewallRulePublic = {
    pos: number;
    type: string;
    action: string;
    source?: (string | null);
    dest?: (string | null);
    proto?: (string | null);
    dport?: (string | null);
    sport?: (string | null);
    enable?: number;
    comment?: (string | null);
    /**
     * 是否由 Campus Cloud 管理（comment 含 campus-cloud: 前綴）
     */
    is_managed?: boolean;
};

/**
 * 更新防火牆規則
 */
export type FirewallRuleUpdate = {
    action?: ('ACCEPT' | 'DROP' | 'REJECT' | null);
    source?: (string | null);
    dest?: (string | null);
    proto?: (string | null);
    dport?: (string | null);
    sport?: (string | null);
    enable?: (number | null);
    comment?: (string | null);
};

/**
 * 建立群組
 */
export type GroupCreate = {
    name: string;
    description?: (string | null);
};

/**
 * 群組詳情（含成員列表）
 */
export type GroupDetailPublic = {
    id: string;
    name: string;
    description?: (string | null);
    owner_id: string;
    created_at?: (string | null);
    members?: Array<GroupMemberPublic>;
};

/**
 * 新增群組成員
 */
export type GroupMemberAdd = {
    emails: Array<(string)>;
};

/**
 * 群組成員資料
 */
export type GroupMemberPublic = {
    user_id: string;
    email: string;
    full_name?: (string | null);
    added_at?: (string | null);
};

/**
 * API 回傳的群組資料
 */
export type GroupPublic = {
    id: string;
    name: string;
    description?: (string | null);
    owner_id: string;
    created_at?: (string | null);
    member_count?: number;
};

/**
 * 群組列表回應
 */
export type GroupsPublic = {
    data: Array<GroupPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 更新節點位置
 */
export type LayoutNodeUpdate = {
    /**
     * VM ID；None 代表 gateway
     */
    vmid?: (number | null);
    /**
     * 節點類型
     */
    node_type: 'vm' | 'gateway';
    /**
     * X 座標
     */
    position_x: number;
    /**
     * Y 座標
     */
    position_y: number;
};

/**
 * 節點類型
 */
export type node_type = 'vm' | 'gateway';

/**
 * 批次更新圖形佈局
 */
export type LayoutUpdate = {
    nodes: Array<LayoutNodeUpdate>;
};

/**
 * 建立 LXC 容器
 */
export type LXCCreateRequest = {
    hostname: string;
    ostemplate: string;
    cores?: number;
    memory?: number;
    rootfs_size?: number;
    password: string;
    storage?: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    start?: boolean;
    unprivileged?: boolean;
};

/**
 * 建立 LXC 回應
 */
export type LXCCreateResponse = {
    vmid: number;
    upid: string;
    message: string;
};

export type MachineCurrentStatus = {
    node: string;
    status: string;
    candidate: boolean;
    running_resources?: number;
    cpu_usage_ratio?: number;
    memory_usage_ratio?: number;
    disk_usage_ratio?: number;
    allocatable_cpu_cores?: number;
    allocatable_memory_gb?: number;
    allocatable_disk_gb?: number;
    gpu_count?: number;
};

/**
 * 通用訊息回應
 */
export type Message = {
    message: string;
};

/**
 * 重設密碼請求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Proxmox 節點資訊
 */
export type NodeSchema = {
    node: string;
    status: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

export type PlacementAdvisorResponse = {
    generated_at?: string;
    reply: string;
    machines_to_open?: Array<RecommendedMachine>;
    reasons?: Array<(string)>;
    current_status?: Array<MachineCurrentStatus>;
    ai_used?: boolean;
    model?: (string | null);
    warning?: (string | null);
    ai_metrics?: (AiMetrics | null);
};

export type PlacementRequest = {
    resource_type?: 'lxc' | 'vm';
    cpu_cores?: number;
    memory_mb?: number;
    disk_gb?: number;
    instance_count?: number;
    gpu_required?: number;
};

export type resource_type = 'lxc' | 'vm';

/**
 * 端口規格（port=0 表示無端口協定，如 icmp/esp 等）
 */
export type PortSpec = {
    /**
     * 端口號；0 表示無端口協定
     */
    port: number;
    /**
     * 協定 (tcp/udp/icmp/esp/ah/...)
     */
    protocol?: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 回傳給前端的 Proxmox 設定（不含密碼與憑證原文）
 */
export type ProxmoxConfigPublic = {
    host: string;
    user: string;
    verify_ssl: boolean;
    iso_storage: string;
    data_storage: string;
    api_timeout: number;
    task_check_interval: number;
    pool_name: string;
    gateway_ip?: (string | null);
    local_subnet?: (string | null);
    updated_at?: (string | null);
    is_configured: boolean;
    has_ca_cert: boolean;
    ca_fingerprint?: (string | null);
};

/**
 * 更新 Proxmox 設定的請求 schema
 */
export type ProxmoxConfigUpdate = {
    host: string;
    user: string;
    password?: (string | null);
    verify_ssl?: boolean;
    iso_storage?: string;
    data_storage?: string;
    api_timeout?: number;
    task_check_interval?: number;
    pool_name?: string;
    ca_cert?: (string | null);
    gateway_ip: string;
    local_subnet?: (string | null);
};

/**
 * 連線測試結果
 */
export type ProxmoxConnectionTestResult = {
    success: boolean;
    message: string;
};

/**
 * 回傳給前端的節點資訊
 */
export type ProxmoxNodePublic = {
    id?: (number | null);
    name: string;
    host: string;
    port: number;
    is_primary: boolean;
    is_online: boolean;
    last_checked?: (string | null);
};

export type RecommendedMachine = {
    node: string;
    resource_type: 'lxc' | 'vm';
    instance_count?: number;
    reason: string;
};

/**
 * 公開的資源資訊（合併 Proxmox + DB）
 */
export type ResourcePublic = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    environment_type?: (string | null);
    os_info?: (string | null);
    expiry_date?: (string | null);
    ip_address?: (string | null);
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

/**
 * RRD 數據點
 */
export type RRDDataPoint = {
    /**
     * Timestamp
     */
    time: number;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    disk?: (number | null);
    maxdisk?: (number | null);
    netin?: (number | null);
    netout?: (number | null);
};

/**
 * RRD 歷史數據
 */
export type RRDDataResponse = {
    /**
     * Time range
     */
    timeframe: string;
    /**
     * Data points
     */
    data: Array<RRDDataPoint>;
};

/**
 * 服務模板無人值守部署請求
 */
export type ScriptDeployRequest = {
    /**
     * 模板 slug（如 docker）
     */
    template_slug: string;
    /**
     * 腳本路徑（如 ct/docker.sh）
     */
    script_path: string;
    hostname: string;
    password: string;
    cpu?: number;
    ram?: number;
    disk?: number;
    unprivileged?: boolean;
    ssh?: boolean;
    environment_type?: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
};

/**
 * 部署任務建立回應
 */
export type ScriptDeployResponse = {
    task_id: string;
    message: string;
};

/**
 * 部署任務狀態
 */
export type ScriptDeployStatus = {
    task_id: string;
    status: string;
    progress?: (string | null);
    vmid?: (number | null);
    message?: (string | null);
    error?: (string | null);
    output?: (string | null);
};

/**
 * 建立快照
 */
export type SnapshotCreateRequest = {
    /**
     * Snapshot name
     */
    snapname: string;
    /**
     * Snapshot description
     */
    description?: (string | null);
    /**
     * Include RAM state (VM only)
     */
    vmstate?: boolean;
};

/**
 * 快照資訊
 */
export type SnapshotInfo = {
    /**
     * Snapshot name
     */
    name: string;
    /**
     * Snapshot description
     */
    description?: (string | null);
    /**
     * Creation timestamp
     */
    snaptime?: (number | null);
    /**
     * Includes VM state (0/1)
     */
    vmstate?: (number | null);
};

/**
 * 快照操作回應
 */
export type SnapshotResponse = {
    message: string;
    task_id?: (string | null);
};

/**
 * 建立規格調整申請
 */
export type SpecChangeRequestCreate = {
    vmid: number;
    change_type: SpecChangeType;
    /**
     * 調整原因至少10字
     */
    reason: string;
    requested_cpu?: (number | null);
    requested_memory?: (number | null);
    requested_disk?: (number | null);
};

/**
 * 公開的規格調整申請資訊
 */
export type SpecChangeRequestPublic = {
    id: string;
    vmid: number;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    change_type: SpecChangeType;
    reason: string;
    current_cpu: (number | null);
    current_memory: (number | null);
    current_disk: (number | null);
    requested_cpu: (number | null);
    requested_memory: (number | null);
    requested_disk: (number | null);
    status: SpecChangeRequestStatus;
    reviewer_id: (string | null);
    review_comment: (string | null);
    reviewed_at: (string | null);
    applied_at: (string | null);
    created_at: string;
};

/**
 * 審核規格調整申請
 */
export type SpecChangeRequestReview = {
    status: SpecChangeRequestStatus;
    review_comment?: (string | null);
};

/**
 * 規格調整申請列表
 */
export type SpecChangeRequestsPublic = {
    data: Array<SpecChangeRequestPublic>;
    count: number;
};

/**
 * 規格調整申請狀態
 */
export type SpecChangeRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * 規格調整類型
 */
export type SpecChangeType = 'cpu' | 'memory' | 'disk' | 'combined';

/**
 * LXC OS template 資訊
 */
export type TemplateSchema = {
    volid: string;
    format: string;
    size: number;
};

/**
 * LXC Terminal 連線資訊
 */
export type TerminalInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

/**
 * JWT 存取權杖回應
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 拓撲圖中的連線
 */
export type TopologyEdge = {
    source_vmid?: (number | null);
    target_vmid?: (number | null);
    ports?: Array<PortSpec>;
    direction?: 'one_way' | 'bidirectional';
};

/**
 * 拓撲圖中的節點
 */
export type TopologyNode = {
    vmid?: (number | null);
    name: string;
    node_type: 'vm' | 'gateway';
    status?: (string | null);
    ip_address?: (string | null);
    firewall_enabled?: boolean;
    position_x?: number;
    position_y?: number;
};

/**
 * 完整拓撲資料（節點 + 連線）
 */
export type TopologyResponse = {
    nodes: Array<TopologyNode>;
    edges: Array<TopologyEdge>;
};

/**
 * 更新密碼
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 建立使用者
 */
export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean;
    role?: UserRole;
    is_superuser?: boolean;
    full_name?: (string | null);
    avatar_url?: (string | null);
};

/**
 * API 回傳的使用者資料
 */
export type UserPublic = {
    id: string;
    email: string;
    is_active: boolean;
    role: UserRole;
    is_superuser: boolean;
    full_name?: (string | null);
    avatar_url?: (string | null);
    created_at?: (string | null);
};

/**
 * 使用者自行註冊
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    avatar_url?: (string | null);
};

export type UserRole = 'student' | 'teacher' | 'admin';

/**
 * 使用者列表回應
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 管理員更新使用者
 */
export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    role?: (UserRole | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    avatar_url?: (string | null);
};

/**
 * 使用者更新自己資料
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    avatar_url?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * 建立 VM（cloud-init template）
 */
export type VMCreateRequest = {
    hostname: string;
    template_id: number;
    username: string;
    password: string;
    cores?: number;
    memory?: number;
    disk_size?: number;
    storage?: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    start?: boolean;
};

/**
 * 建立 VM 回應
 */
export type VMCreateResponse = {
    vmid: number;
    upid: string;
    message: string;
};

/**
 * 提交虛擬機申請
 */
export type VMRequestCreate = {
    reason: string;
    resource_type: string;
    hostname: string;
    cores?: number;
    memory?: number;
    password: string;
    storage?: string;
    environment_type?: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    ostemplate?: (string | null);
    rootfs_size?: (number | null);
    template_id?: (number | null);
    disk_size?: (number | null);
    username?: (string | null);
};

/**
 * 公開的虛擬機申請資訊
 */
export type VMRequestPublic = {
    id: string;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    reason: string;
    resource_type: string;
    hostname: string;
    cores: number;
    memory: number;
    storage: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    ostemplate?: (string | null);
    rootfs_size?: (number | null);
    template_id?: (number | null);
    disk_size?: (number | null);
    username?: (string | null);
    status: VMRequestStatus;
    reviewer_id?: (string | null);
    review_comment?: (string | null);
    reviewed_at?: (string | null);
    vmid?: (number | null);
    created_at: string;
};

/**
 * 審核虛擬機申請
 */
export type VMRequestReview = {
    status: VMRequestStatus;
    review_comment?: (string | null);
};

/**
 * 虛擬機申請列表
 */
export type VMRequestsPublic = {
    data: Array<VMRequestPublic>;
    count: number;
};

/**
 * 虛擬機申請狀態
 */
export type VMRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * 虛擬機資訊
 */
export type VMSchema = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
    netin?: (number | null);
    diskread?: (number | null);
    diskwrite?: (number | null);
    disk?: (number | null);
    template?: (number | null);
    memhost?: (number | null);
    maxdisk?: (number | null);
};

/**
 * VM template 資訊
 */
export type VMTemplateSchema = {
    vmid: number;
    name: string;
    node: string;
};

/**
 * VNC 連線資訊
 */
export type VNCInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

export type AiApiCreateAiApiRequestData = {
    requestBody: AIAPIRequestCreate;
};

export type AiApiCreateAiApiRequestResponse = (AIAPIRequestPublic);

export type AiApiListAllAiApiRequestsData = {
    limit?: number;
    skip?: number;
    status?: (AIAPIRequestStatus | null);
};

export type AiApiListAllAiApiRequestsResponse = (AIAPIRequestsPublic);

export type AiApiListMyAiApiRequestsData = {
    limit?: number;
    skip?: number;
};

export type AiApiListMyAiApiRequestsResponse = (AIAPIRequestsPublic);

export type AiApiGetAiApiRequestData = {
    requestId: string;
};

export type AiApiGetAiApiRequestResponse = (AIAPIRequestPublic);

export type AiApiReviewAiApiRequestData = {
    requestBody: AIAPIRequestReview;
    requestId: string;
};

export type AiApiReviewAiApiRequestResponse = (AIAPIRequestPublic);

export type AiApiListMyAiApiCredentialsData = {
    limit?: number;
    skip?: number;
};

export type AiApiListMyAiApiCredentialsResponse = (AIAPICredentialsPublic);

export type AiApiRotateMyAiApiCredentialData = {
    credentialId: string;
};

export type AiApiRotateMyAiApiCredentialResponse = (AIAPICredentialPublic);

export type AiApiDeleteMyAiApiCredentialData = {
    credentialId: string;
};

export type AiApiDeleteMyAiApiCredentialResponse = (Message);

export type AiPveAdvisorRecommendPlacementData = {
    requestBody: PlacementRequest;
};

export type AiPveAdvisorRecommendPlacementResponse = (PlacementAdvisorResponse);

export type AiTemplateRecommendationChatData = {
    requestBody: ChatRequest;
};

export type AiTemplateRecommendationChatResponse = (ChatResponse);

export type AiTemplateRecommendationRecommendData = {
    requestBody: ChatRequest;
};

export type AiTemplateRecommendationRecommendResponse = ({
    [key: string]: unknown;
});

export type AuditLogsGetAllAuditLogsData = {
    action?: (AuditAction | null);
    limit?: number;
    skip?: number;
    userId?: (string | null);
    vmid?: (number | null);
};

export type AuditLogsGetAllAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsGetMyAuditLogsData = {
    limit?: number;
    skip?: number;
};

export type AuditLogsGetMyAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsGetResourceAuditLogsData = {
    limit?: number;
    skip?: number;
    vmid: number;
};

export type AuditLogsGetResourceAuditLogsResponse = (AuditLogsPublic);

export type FirewallGetTopologyResponse = (TopologyResponse);

export type FirewallGetLayoutResponse = (unknown);

export type FirewallSaveLayoutData = {
    requestBody: LayoutUpdate;
};

export type FirewallSaveLayoutResponse = (Message);

export type FirewallCreateConnectionData = {
    requestBody: ConnectionCreate;
};

export type FirewallCreateConnectionResponse = (Message);

export type FirewallDeleteConnectionData = {
    requestBody: ConnectionDelete;
};

export type FirewallDeleteConnectionResponse = (Message);

export type FirewallListRulesData = {
    vmid: number;
};

export type FirewallListRulesResponse = (Array<FirewallRulePublic>);

export type FirewallCreateRuleData = {
    requestBody: FirewallRuleCreate;
    vmid: number;
};

export type FirewallCreateRuleResponse = (Message);

export type FirewallUpdateRuleData = {
    pos: number;
    requestBody: FirewallRuleUpdate;
    vmid: number;
};

export type FirewallUpdateRuleResponse = (Message);

export type FirewallDeleteRuleData = {
    pos: number;
    vmid: number;
};

export type FirewallDeleteRuleResponse = (Message);

export type FirewallGetOptionsData = {
    vmid: number;
};

export type FirewallGetOptionsResponse = (FirewallOptionsPublic);

export type GroupsListGroupsResponse = (GroupsPublic);

export type GroupsCreateGroupData = {
    requestBody: GroupCreate;
};

export type GroupsCreateGroupResponse = (GroupPublic);

export type GroupsGetGroupData = {
    groupId: string;
};

export type GroupsGetGroupResponse = (GroupDetailPublic);

export type GroupsDeleteGroupData = {
    groupId: string;
};

export type GroupsDeleteGroupResponse = (Message);

export type GroupsAddMembersData = {
    groupId: string;
    requestBody: GroupMemberAdd;
};

export type GroupsAddMembersResponse = (Message);

export type GroupsRemoveMemberData = {
    groupId: string;
    userId: string;
};

export type GroupsRemoveMemberResponse = (Message);

export type GroupsImportMembersFromCsvData = {
    formData: Body_groups_import_members_from_csv;
    groupId: string;
};

export type GroupsImportMembersFromCsvResponse = (CsvImportResult);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LxcGetLxcTerminalData = {
    vmid: number;
};

export type LxcGetLxcTerminalResponse = (TerminalInfoSchema);

export type LxcGetTemplatesResponse = (Array<TemplateSchema>);

export type LxcCreateLxcData = {
    requestBody: LXCCreateRequest;
};

export type LxcCreateLxcResponse = (LXCCreateResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProxmoxConfigGetProxmoxConfigResponse = (ProxmoxConfigPublic);

export type ProxmoxConfigUpdateProxmoxConfigData = {
    requestBody: ProxmoxConfigUpdate;
};

export type ProxmoxConfigUpdateProxmoxConfigResponse = (ProxmoxConfigPublic);

export type ProxmoxConfigPreviewClusterData = {
    requestBody: ProxmoxConfigUpdate;
};

export type ProxmoxConfigPreviewClusterResponse = (ClusterPreviewResult);

export type ProxmoxConfigSyncNodesData = {
    requestBody: Array<ProxmoxNodePublic>;
};

export type ProxmoxConfigSyncNodesResponse = (Array<ProxmoxNodePublic>);

export type ProxmoxConfigGetNodesResponse = (Array<ProxmoxNodePublic>);

export type ProxmoxConfigCheckNodesResponse = (Array<ProxmoxNodePublic>);

export type ProxmoxConfigParseCertData = {
    requestBody: Body_proxmox_config_parse_cert;
};

export type ProxmoxConfigParseCertResponse = (CertParseResult);

export type ProxmoxConfigTestProxmoxConnectionResponse = (ProxmoxConnectionTestResult);

export type ResourceDetailsGetCurrentStatsData = {
    vmid: number;
};

export type ResourceDetailsGetCurrentStatsResponse = (CurrentStatsResponse);

export type ResourceDetailsGetRrdStatsData = {
    timeframe?: string;
    vmid: number;
};

export type ResourceDetailsGetRrdStatsResponse = (RRDDataResponse);

export type ResourceDetailsListSnapshotsData = {
    vmid: number;
};

export type ResourceDetailsListSnapshotsResponse = (Array<SnapshotInfo>);

export type ResourceDetailsCreateSnapshotData = {
    requestBody: SnapshotCreateRequest;
    vmid: number;
};

export type ResourceDetailsCreateSnapshotResponse = (SnapshotResponse);

export type ResourceDetailsDeleteSnapshotData = {
    snapname: string;
    vmid: number;
};

export type ResourceDetailsDeleteSnapshotResponse = (SnapshotResponse);

export type ResourceDetailsRollbackSnapshotData = {
    snapname: string;
    vmid: number;
};

export type ResourceDetailsRollbackSnapshotResponse = (SnapshotResponse);

export type ResourceDetailsDirectUpdateSpecData = {
    requestBody: DirectSpecUpdateRequest;
    vmid: number;
};

export type ResourceDetailsDirectUpdateSpecResponse = (unknown);

export type ResourcesListNodesResponse = (Array<NodeSchema>);

export type ResourcesListResourcesData = {
    node?: (string | null);
};

export type ResourcesListResourcesResponse = (Array<ResourcePublic>);

export type ResourcesListMyResourcesResponse = (Array<ResourcePublic>);

export type ResourcesGetResourceData = {
    vmid: number;
};

export type ResourcesGetResourceResponse = (VMSchema);

export type ResourcesDeleteResourceData = {
    force?: boolean;
    purge?: boolean;
    vmid: number;
};

export type ResourcesDeleteResourceResponse = (unknown);

export type ResourcesGetResourceConfigData = {
    vmid: number;
};

export type ResourcesGetResourceConfigResponse = (unknown);

export type ResourcesStartResourceData = {
    vmid: number;
};

export type ResourcesStartResourceResponse = (unknown);

export type ResourcesStopResourceData = {
    vmid: number;
};

export type ResourcesStopResourceResponse = (unknown);

export type ResourcesRebootResourceData = {
    vmid: number;
};

export type ResourcesRebootResourceResponse = (unknown);

export type ResourcesShutdownResourceData = {
    vmid: number;
};

export type ResourcesShutdownResourceResponse = (unknown);

export type ResourcesResetResourceData = {
    vmid: number;
};

export type ResourcesResetResourceResponse = (unknown);

export type ScriptDeployDeployServiceTemplateData = {
    requestBody: ScriptDeployRequest;
};

export type ScriptDeployDeployServiceTemplateResponse = (ScriptDeployResponse);

export type ScriptDeployGetDeployStatusData = {
    taskId: string;
};

export type ScriptDeployGetDeployStatusResponse = (ScriptDeployStatus);

export type ScriptDeployRegisterDeployedResourceData = {
    taskId: string;
};

export type ScriptDeployRegisterDeployedResourceResponse = ({
    [key: string]: unknown;
});

export type SpecChangeRequestsCreateSpecChangeRequestData = {
    requestBody: SpecChangeRequestCreate;
};

export type SpecChangeRequestsCreateSpecChangeRequestResponse = (SpecChangeRequestPublic);

export type SpecChangeRequestsGetAllSpecChangeRequestsData = {
    limit?: number;
    skip?: number;
    status?: (SpecChangeRequestStatus | null);
    vmid?: (number | null);
};

export type SpecChangeRequestsGetAllSpecChangeRequestsResponse = (SpecChangeRequestsPublic);

export type SpecChangeRequestsGetMySpecChangeRequestsData = {
    limit?: number;
    skip?: number;
};

export type SpecChangeRequestsGetMySpecChangeRequestsResponse = (SpecChangeRequestsPublic);

export type SpecChangeRequestsReviewSpecChangeRequestData = {
    requestBody: SpecChangeRequestReview;
    requestId: string;
};

export type SpecChangeRequestsReviewSpecChangeRequestResponse = (SpecChangeRequestPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type VmGetVmConsoleData = {
    vmid: number;
};

export type VmGetVmConsoleResponse = (VNCInfoSchema);

export type VmCreateVmData = {
    requestBody: VMCreateRequest;
};

export type VmCreateVmResponse = (VMCreateResponse);

export type VmGetVmTemplatesResponse = (Array<VMTemplateSchema>);

export type VmRequestsCreateVmRequestData = {
    requestBody: VMRequestCreate;
};

export type VmRequestsCreateVmRequestResponse = (VMRequestPublic);

export type VmRequestsListAllVmRequestsData = {
    limit?: number;
    skip?: number;
    status?: (VMRequestStatus | null);
};

export type VmRequestsListAllVmRequestsResponse = (VMRequestsPublic);

export type VmRequestsListMyVmRequestsData = {
    limit?: number;
    skip?: number;
};

export type VmRequestsListMyVmRequestsResponse = (VMRequestsPublic);

export type VmRequestsGetVmRequestData = {
    requestId: string;
};

export type VmRequestsGetVmRequestResponse = (VMRequestPublic);

export type VmRequestsReviewVmRequestData = {
    requestBody: VMRequestReview;
    requestId: string;
};

export type VmRequestsReviewVmRequestResponse = (VMRequestPublic);