// This file is auto-generated by @hey-api/openapi-ts

/**
 * 審計操作類型
 */
export type AuditAction = 'spec_change_request' | 'spec_change_apply' | 'snapshot_create' | 'snapshot_delete' | 'snapshot_rollback' | 'config_update' | 'vm_create' | 'lxc_create' | 'resource_start' | 'resource_stop' | 'resource_reboot' | 'resource_shutdown' | 'resource_reset' | 'resource_delete' | 'vm_request_submit' | 'vm_request_review' | 'user_create' | 'user_update' | 'user_delete';

/**
 * 公開的審計日誌資訊
 */
export type AuditLogPublic = {
    id: string;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    vmid: (number | null);
    action: AuditAction;
    details: string;
    ip_address: (string | null);
    user_agent: (string | null);
    created_at: string;
};

/**
 * 審計日誌列表
 */
export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 當前實時狀態
 */
export type CurrentStatsResponse = {
    /**
     * CPU 使用率 (0-1)
     */
    cpu?: (number | null);
    /**
     * CPU 核心數
     */
    maxcpu?: (number | null);
    /**
     * 當前記憶體使用 (bytes)
     */
    mem?: (number | null);
    /**
     * 最大記憶體 (bytes)
     */
    maxmem?: (number | null);
    /**
     * 當前磁碟使用 (bytes)
     */
    disk?: (number | null);
    /**
     * 最大磁碟 (bytes)
     */
    maxdisk?: (number | null);
    /**
     * 網絡輸入 (bytes)
     */
    netin?: (number | null);
    /**
     * 網絡輸出 (bytes)
     */
    netout?: (number | null);
    /**
     * 運行時間 (seconds)
     */
    uptime?: (number | null);
    /**
     * 狀態 (running, stopped, etc.)
     */
    status: string;
};

/**
 * 管理員直接調整規格
 */
export type DirectSpecUpdateRequest = {
    /**
     * CPU 核心數
     */
    cores?: (number | null);
    /**
     * 記憶體 (MB)
     */
    memory?: (number | null);
    /**
     * 磁碟大小增量 (例如 "+10G"，僅能增加)
     */
    disk_size?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response after creating LXC container.
 */
export type LXCCreateResponse = {
    vmid: number;
    upid: string;
    message: string;
};

/**
 * Schema for creating a new LXC container.
 */
export type LXCCreateSchema = {
    hostname: string;
    ostemplate: string;
    cores?: number;
    memory?: number;
    rootfs_size?: number;
    password: string;
    storage?: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    start?: boolean;
    unprivileged?: boolean;
};

/**
 * 通用訊息回應
 */
export type Message = {
    message: string;
};

/**
 * 重設密碼請求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Proxmox node information.
 */
export type NodeSchema = {
    node: string;
    status: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 公開的資源資訊，合併Proxmox資料和資料庫額外資訊.
 */
export type ResourcePublic = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    environment_type?: (string | null);
    os_info?: (string | null);
    expiry_date?: (string | null);
    ip_address?: (string | null);
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

/**
 * RRD 數據點
 */
export type RRDDataPoint = {
    /**
     * 時間戳
     */
    time: number;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    disk?: (number | null);
    maxdisk?: (number | null);
    netin?: (number | null);
    netout?: (number | null);
};

/**
 * RRD 歷史數據響應
 */
export type RRDDataResponse = {
    /**
     * 時間範圍
     */
    timeframe: string;
    /**
     * 數據點列表
     */
    data: Array<RRDDataPoint>;
};

/**
 * 創建快照請求
 */
export type SnapshotCreateRequest = {
    /**
     * 快照名稱
     */
    snapname: string;
    /**
     * 快照描述
     */
    description?: (string | null);
    /**
     * 是否包含 RAM 狀態 (僅 VM)
     */
    vmstate?: boolean;
};

/**
 * 快照信息
 */
export type SnapshotInfo = {
    /**
     * 快照名稱
     */
    name: string;
    /**
     * 快照描述
     */
    description?: (string | null);
    /**
     * 創建時間戳
     */
    snaptime?: (number | null);
    /**
     * 是否包含 VM 狀態 (0/1)
     */
    vmstate?: (number | null);
};

/**
 * 快照操作響應
 */
export type SnapshotResponse = {
    message: string;
    task_id?: (string | null);
};

/**
 * 創建規格調整申請
 */
export type SpecChangeRequestCreate = {
    vmid: number;
    change_type: SpecChangeType;
    /**
     * 調整原因至少10字
     */
    reason: string;
    requested_cpu?: (number | null);
    requested_memory?: (number | null);
    requested_disk?: (number | null);
};

/**
 * 公開的規格調整申請資訊
 */
export type SpecChangeRequestPublic = {
    id: string;
    vmid: number;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    change_type: SpecChangeType;
    reason: string;
    current_cpu: (number | null);
    current_memory: (number | null);
    current_disk: (number | null);
    requested_cpu: (number | null);
    requested_memory: (number | null);
    requested_disk: (number | null);
    status: SpecChangeRequestStatus;
    reviewer_id: (string | null);
    review_comment: (string | null);
    reviewed_at: (string | null);
    applied_at: (string | null);
    created_at: string;
};

/**
 * 審核規格調整申請
 */
export type SpecChangeRequestReview = {
    status: SpecChangeRequestStatus;
    review_comment?: (string | null);
};

/**
 * 規格調整申請列表
 */
export type SpecChangeRequestsPublic = {
    data: Array<SpecChangeRequestPublic>;
    count: number;
};

/**
 * 規格調整申請狀態
 */
export type SpecChangeRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * 規格調整類型
 */
export type SpecChangeType = 'cpu' | 'memory' | 'disk' | 'combined';

/**
 * OS template information.
 */
export type TemplateSchema = {
    volid: string;
    format: string;
    size: number;
};

/**
 * Terminal console connection information for LXC containers.
 */
export type TerminalInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

/**
 * JWT 存取權杖回應
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 更新密碼請求
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 建立使用者時接收的資料
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * API 回傳的使用者資料
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 使用者自行註冊時使用的資料
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * API 回傳的使用者列表
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 更新使用者時接收的資料
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 使用者更新自己資料時使用
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Response after creating VM.
 */
export type VMCreateResponse = {
    vmid: number;
    upid: string;
    message: string;
};

/**
 * Schema for creating a new VM from cloud-init template.
 */
export type VMCreateSchema = {
    hostname: string;
    template_id: number;
    username: string;
    password: string;
    cores?: number;
    memory?: number;
    disk_size?: number;
    storage?: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    start?: boolean;
};

/**
 * 建立虛擬機申請的 Schema.
 */
export type VMRequestCreate = {
    reason: string;
    resource_type: string;
    hostname: string;
    cores?: number;
    memory?: number;
    password: string;
    storage?: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    ostemplate?: (string | null);
    rootfs_size?: (number | null);
    template_id?: (number | null);
    disk_size?: (number | null);
    username?: (string | null);
};

/**
 * 公開的虛擬機申請資訊.
 */
export type VMRequestPublic = {
    id: string;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    reason: string;
    resource_type: string;
    hostname: string;
    cores: number;
    memory: number;
    storage: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    ostemplate?: (string | null);
    rootfs_size?: (number | null);
    template_id?: (number | null);
    disk_size?: (number | null);
    username?: (string | null);
    status: VMRequestStatus;
    reviewer_id?: (string | null);
    review_comment?: (string | null);
    reviewed_at?: (string | null);
    vmid?: (number | null);
    created_at: string;
};

/**
 * 審核虛擬機申請的 Schema.
 */
export type VMRequestReview = {
    status: VMRequestStatus;
    review_comment?: (string | null);
};

/**
 * 虛擬機申請列表.
 */
export type VMRequestsPublic = {
    data: Array<VMRequestPublic>;
    count: number;
};

/**
 * 虛擬機申請狀態
 */
export type VMRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * Virtual machine information.
 */
export type VMSchema = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
    netin?: (number | null);
    diskread?: (number | null);
    diskwrite?: (number | null);
    disk?: (number | null);
    template?: (number | null);
    memhost?: (number | null);
    maxdisk?: (number | null);
};

/**
 * VM template information.
 */
export type VMTemplateSchema = {
    vmid: number;
    name: string;
    node: string;
};

/**
 * VNC console connection information.
 */
export type VNCInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

export type AuditLogsGetAllAuditLogsData = {
    action?: (AuditAction | null);
    limit?: number;
    skip?: number;
    userId?: (string | null);
    vmid?: (number | null);
};

export type AuditLogsGetAllAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsGetMyAuditLogsData = {
    limit?: number;
    skip?: number;
};

export type AuditLogsGetMyAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsGetResourceAuditLogsData = {
    limit?: number;
    skip?: number;
    vmid: number;
};

export type AuditLogsGetResourceAuditLogsResponse = (AuditLogsPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LxcGetLxcTerminalData = {
    vmid: number;
};

export type LxcGetLxcTerminalResponse = (TerminalInfoSchema);

export type LxcGetTemplatesResponse = (Array<TemplateSchema>);

export type LxcCreateLxcData = {
    requestBody: LXCCreateSchema;
};

export type LxcCreateLxcResponse = (LXCCreateResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResourceDetailsGetCurrentStatsData = {
    vmid: number;
};

export type ResourceDetailsGetCurrentStatsResponse = (CurrentStatsResponse);

export type ResourceDetailsGetRrdStatsData = {
    timeframe?: string;
    vmid: number;
};

export type ResourceDetailsGetRrdStatsResponse = (RRDDataResponse);

export type ResourceDetailsListSnapshotsData = {
    vmid: number;
};

export type ResourceDetailsListSnapshotsResponse = (Array<SnapshotInfo>);

export type ResourceDetailsCreateSnapshotData = {
    requestBody: SnapshotCreateRequest;
    vmid: number;
};

export type ResourceDetailsCreateSnapshotResponse = (SnapshotResponse);

export type ResourceDetailsDeleteSnapshotData = {
    snapname: string;
    vmid: number;
};

export type ResourceDetailsDeleteSnapshotResponse = (SnapshotResponse);

export type ResourceDetailsRollbackSnapshotData = {
    snapname: string;
    vmid: number;
};

export type ResourceDetailsRollbackSnapshotResponse = (SnapshotResponse);

export type ResourceDetailsDirectUpdateSpecData = {
    requestBody: DirectSpecUpdateRequest;
    vmid: number;
};

export type ResourceDetailsDirectUpdateSpecResponse = (unknown);

export type ResourcesListNodesResponse = (Array<NodeSchema>);

export type ResourcesListResourcesData = {
    node?: (string | null);
};

export type ResourcesListResourcesResponse = (Array<ResourcePublic>);

export type ResourcesListMyResourcesResponse = (Array<ResourcePublic>);

export type ResourcesGetResourceData = {
    vmid: number;
};

export type ResourcesGetResourceResponse = (VMSchema);

export type ResourcesDeleteResourceData = {
    force?: boolean;
    purge?: boolean;
    vmid: number;
};

export type ResourcesDeleteResourceResponse = (unknown);

export type ResourcesGetResourceConfigData = {
    vmid: number;
};

export type ResourcesGetResourceConfigResponse = (unknown);

export type ResourcesStartResourceData = {
    vmid: number;
};

export type ResourcesStartResourceResponse = (unknown);

export type ResourcesStopResourceData = {
    vmid: number;
};

export type ResourcesStopResourceResponse = (unknown);

export type ResourcesRebootResourceData = {
    vmid: number;
};

export type ResourcesRebootResourceResponse = (unknown);

export type ResourcesShutdownResourceData = {
    vmid: number;
};

export type ResourcesShutdownResourceResponse = (unknown);

export type ResourcesResetResourceData = {
    vmid: number;
};

export type ResourcesResetResourceResponse = (unknown);

export type SpecChangeRequestsCreateSpecChangeRequestData = {
    requestBody: SpecChangeRequestCreate;
    vmid: number;
};

export type SpecChangeRequestsCreateSpecChangeRequestResponse = (SpecChangeRequestPublic);

export type SpecChangeRequestsGetAllSpecChangeRequestsData = {
    limit?: number;
    skip?: number;
    status?: (SpecChangeRequestStatus | null);
    vmid?: (number | null);
};

export type SpecChangeRequestsGetAllSpecChangeRequestsResponse = (SpecChangeRequestsPublic);

export type SpecChangeRequestsGetMySpecChangeRequestsData = {
    limit?: number;
    skip?: number;
};

export type SpecChangeRequestsGetMySpecChangeRequestsResponse = (SpecChangeRequestsPublic);

export type SpecChangeRequestsReviewSpecChangeRequestData = {
    requestBody: SpecChangeRequestReview;
    requestId: string;
};

export type SpecChangeRequestsReviewSpecChangeRequestResponse = (SpecChangeRequestPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type VmGetVmConsoleData = {
    vmid: number;
};

export type VmGetVmConsoleResponse = (VNCInfoSchema);

export type VmCreateVmData = {
    requestBody: VMCreateSchema;
};

export type VmCreateVmResponse = (VMCreateResponse);

export type VmGetVmTemplatesResponse = (Array<VMTemplateSchema>);

export type VmRequestsCreateVmRequestData = {
    requestBody: VMRequestCreate;
};

export type VmRequestsCreateVmRequestResponse = (VMRequestPublic);

export type VmRequestsListAllVmRequestsData = {
    limit?: number;
    skip?: number;
    status?: (VMRequestStatus | null);
};

export type VmRequestsListAllVmRequestsResponse = (VMRequestsPublic);

export type VmRequestsListMyVmRequestsData = {
    limit?: number;
    skip?: number;
};

export type VmRequestsListMyVmRequestsResponse = (VMRequestsPublic);

export type VmRequestsGetVmRequestData = {
    requestId: string;
};

export type VmRequestsGetVmRequestResponse = (VMRequestPublic);

export type VmRequestsReviewVmRequestData = {
    requestBody: VMRequestReview;
    requestId: string;
};

export type VmRequestsReviewVmRequestResponse = (VMRequestPublic);