"""add deletion_requests table

Revision ID: d4ffdd95ee6e
Revises: dfb01_extra_block
Create Date: 2026-04-20 00:53:49.246049

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4ffdd95ee6e"
down_revision = "dfb01_extra_block"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "deletion_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vmid", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("node", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("purge", sa.Boolean(), nullable=False),
        sa.Column("force", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="deletionrequeststatus",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deletion_requests_user_id"),
        "deletion_requests",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deletion_requests_vmid"),
        "deletion_requests",
        ["vmid"],
        unique=False,
    )


def downgrade():
    op.drop_index(op.f("ix_deletion_requests_vmid"), table_name="deletion_requests")
    op.drop_index(op.f("ix_deletion_requests_user_id"), table_name="deletion_requests")
    op.drop_table("deletion_requests")
    sa.Enum(name="deletionrequeststatus").drop(op.get_bind(), checkfirst=True)
"""add deletion_requests table

Revision ID: d4ffdd95ee6e
Revises: dfb01_extra_block
Create Date: 2026-04-20 00:53:49.246049

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4ffdd95ee6e'
down_revision = 'dfb01_extra_block'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_api_rate_limit',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('minute_key', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'minute_key')
    )
    op.create_index(op.f('ix_ai_api_rate_limit_updated_at'), 'ai_api_rate_limit', ['updated_at'], unique=False)
    op.create_table('deletion_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vmid', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purge', sa.Boolean(), nullable=False),
    sa.Column('force', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='deletionrequeststatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_user_id'), 'deletion_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_vmid'), 'deletion_requests', ['vmid'], unique=False)
    op.alter_column('ai_api_requests', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='每分鐘請求限制（1-1000），None 使用預設值 20',
               existing_nullable=True)
    op.drop_constraint(op.f('firewall_layout_user_id_fkey'), 'firewall_layout', type_='foreignkey')
    op.create_foreign_key(None, 'firewall_layout', 'user', ['user_id'], ['id'])
    op.alter_column('group', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_group_owner_id'), table_name='group')
    op.drop_constraint(op.f('group_owner_id_fkey'), 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['owner_id'], ['id'])
    op.alter_column('group_member', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('group_member_user_id_fkey'), 'group_member', type_='foreignkey')
    op.drop_constraint(op.f('group_member_group_id_fkey'), 'group_member', type_='foreignkey')
    op.create_foreign_key(None, 'group_member', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'group_member', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('script_deploy_logs_task_id_key'), 'script_deploy_logs', type_='unique')
    op.drop_index(op.f('ix_script_deploy_logs_task_id'), table_name='script_deploy_logs')
    op.create_index(op.f('ix_script_deploy_logs_task_id'), 'script_deploy_logs', ['task_id'], unique=True)
    op.drop_index(op.f('ix_tunnel_proxies_proxy_name'), table_name='tunnel_proxies')
    op.alter_column('vm_requests', 'resource_warning',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vm_requests', 'resource_warning',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_tunnel_proxies_proxy_name'), 'tunnel_proxies', ['proxy_name'], unique=True)
    op.drop_index(op.f('ix_script_deploy_logs_task_id'), table_name='script_deploy_logs')
    op.create_index(op.f('ix_script_deploy_logs_task_id'), 'script_deploy_logs', ['task_id'], unique=False)
    op.create_unique_constraint(op.f('script_deploy_logs_task_id_key'), 'script_deploy_logs', ['task_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'group_member', type_='foreignkey')
    op.drop_constraint(None, 'group_member', type_='foreignkey')
    op.create_foreign_key(op.f('group_member_group_id_fkey'), 'group_member', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('group_member_user_id_fkey'), 'group_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('group_member', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key(op.f('group_owner_id_fkey'), 'group', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_group_owner_id'), 'group', ['owner_id'], unique=False)
    op.alter_column('group', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'firewall_layout', type_='foreignkey')
    op.create_foreign_key(op.f('firewall_layout_user_id_fkey'), 'firewall_layout', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_api_requests', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment='每分鐘請求限制（1-1000），None 使用預設值 20',
               existing_nullable=True)
    op.drop_index(op.f('ix_deletion_requests_vmid'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_user_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_ai_api_rate_limit_updated_at'), table_name='ai_api_rate_limit')
    op.drop_table('ai_api_rate_limit')
    # ### end Alembic commands ###
