"""add_spec_change_requests_and_audit_logs

Revision ID: e48bab2b8407
Revises: 883012a55f1e
Create Date: 2026-02-24 10:15:25.308222

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e48bab2b8407'
down_revision = '883012a55f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vmid', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('spec_change_request', 'spec_change_apply', 'snapshot_create', 'snapshot_delete', 'snapshot_rollback', 'config_update', 'vm_create', 'lxc_create', 'resource_start', 'resource_stop', 'resource_reboot', 'resource_shutdown', 'resource_reset', 'resource_delete', 'vm_request_submit', 'vm_request_review', 'user_create', 'user_update', 'user_delete', name='auditaction'), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_change_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vmid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.Enum('cpu', 'memory', 'disk', 'combined', name='specchangetype'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_cpu', sa.Integer(), nullable=True),
    sa.Column('current_memory', sa.Integer(), nullable=True),
    sa.Column('current_disk', sa.Integer(), nullable=True),
    sa.Column('requested_cpu', sa.Integer(), nullable=True),
    sa.Column('requested_memory', sa.Integer(), nullable=True),
    sa.Column('requested_disk', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='specchangerequeststatus'), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('review_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_change_requests')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
