/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutResourcesCreateRouteImport } from './routes/_layout/resources-create'
import { Route as LayoutResourcesRouteImport } from './routes/_layout/resources'
import { Route as LayoutMyResourcesRouteImport } from './routes/_layout/my-resources'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutFirewallRouteImport } from './routes/_layout/firewall'
import { Route as LayoutApprovalsRouteImport } from './routes/_layout/approvals'
import { Route as LayoutApplicationsCreateRouteImport } from './routes/_layout/applications-create'
import { Route as LayoutApplicationsRouteImport } from './routes/_layout/applications'
import { Route as LayoutAiApiApprovalsRouteImport } from './routes/_layout/ai-api-approvals'
import { Route as LayoutAiApiRouteImport } from './routes/_layout/ai-api'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutResourcesVmidRouteImport } from './routes/_layout/resources_.$vmid'
import { Route as LayoutMyResourcesVmidRouteImport } from './routes/_layout/my-resources_.$vmid'
import { Route as LayoutGroupsGroupIdRouteImport } from './routes/_layout/groups_.$groupId'
import { Route as LayoutApprovalsRequestIdRouteImport } from './routes/_layout/approvals_.$requestId'
import { Route as LayoutAdminMigrationJobsRouteImport } from './routes/_layout/admin.migration-jobs'
import { Route as LayoutAdminGatewayRouteImport } from './routes/_layout/admin.gateway'
import { Route as LayoutAdminConfigurationRouteImport } from './routes/_layout/admin.configuration'
import { Route as LayoutAdminAuditLogsRouteImport } from './routes/_layout/admin.audit-logs'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesCreateRoute = LayoutResourcesCreateRouteImport.update({
  id: '/resources-create',
  path: '/resources-create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesRoute = LayoutResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyResourcesRoute = LayoutMyResourcesRouteImport.update({
  id: '/my-resources',
  path: '/my-resources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFirewallRoute = LayoutFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApprovalsRoute = LayoutApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsCreateRoute =
  LayoutApplicationsCreateRouteImport.update({
    id: '/applications-create',
    path: '/applications-create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApplicationsRoute = LayoutApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAiApiApprovalsRoute = LayoutAiApiApprovalsRouteImport.update({
  id: '/ai-api-approvals',
  path: '/ai-api-approvals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAiApiRoute = LayoutAiApiRouteImport.update({
  id: '/ai-api',
  path: '/ai-api',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutResourcesVmidRoute = LayoutResourcesVmidRouteImport.update({
  id: '/resources_/$vmid',
  path: '/resources/$vmid',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyResourcesVmidRoute = LayoutMyResourcesVmidRouteImport.update({
  id: '/my-resources_/$vmid',
  path: '/my-resources/$vmid',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsGroupIdRoute = LayoutGroupsGroupIdRouteImport.update({
  id: '/groups_/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApprovalsRequestIdRoute =
  LayoutApprovalsRequestIdRouteImport.update({
    id: '/approvals_/$requestId',
    path: '/approvals/$requestId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminMigrationJobsRoute =
  LayoutAdminMigrationJobsRouteImport.update({
    id: '/migration-jobs',
    path: '/migration-jobs',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminGatewayRoute = LayoutAdminGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminConfigurationRoute =
  LayoutAdminConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminAuditLogsRoute = LayoutAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/ai-api': typeof LayoutAiApiRoute
  '/ai-api-approvals': typeof LayoutAiApiApprovalsRoute
  '/applications': typeof LayoutApplicationsRoute
  '/applications-create': typeof LayoutApplicationsCreateRoute
  '/approvals': typeof LayoutApprovalsRoute
  '/firewall': typeof LayoutFirewallRoute
  '/groups': typeof LayoutGroupsRoute
  '/my-resources': typeof LayoutMyResourcesRoute
  '/resources': typeof LayoutResourcesRoute
  '/resources-create': typeof LayoutResourcesCreateRoute
  '/settings': typeof LayoutSettingsRoute
  '/admin/audit-logs': typeof LayoutAdminAuditLogsRoute
  '/admin/configuration': typeof LayoutAdminConfigurationRoute
  '/admin/gateway': typeof LayoutAdminGatewayRoute
  '/admin/migration-jobs': typeof LayoutAdminMigrationJobsRoute
  '/approvals/$requestId': typeof LayoutApprovalsRequestIdRoute
  '/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/my-resources/$vmid': typeof LayoutMyResourcesVmidRoute
  '/resources/$vmid': typeof LayoutResourcesVmidRoute
  '/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-api': typeof LayoutAiApiRoute
  '/ai-api-approvals': typeof LayoutAiApiApprovalsRoute
  '/applications': typeof LayoutApplicationsRoute
  '/applications-create': typeof LayoutApplicationsCreateRoute
  '/approvals': typeof LayoutApprovalsRoute
  '/firewall': typeof LayoutFirewallRoute
  '/groups': typeof LayoutGroupsRoute
  '/my-resources': typeof LayoutMyResourcesRoute
  '/resources': typeof LayoutResourcesRoute
  '/resources-create': typeof LayoutResourcesCreateRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/audit-logs': typeof LayoutAdminAuditLogsRoute
  '/admin/configuration': typeof LayoutAdminConfigurationRoute
  '/admin/gateway': typeof LayoutAdminGatewayRoute
  '/admin/migration-jobs': typeof LayoutAdminMigrationJobsRoute
  '/approvals/$requestId': typeof LayoutApprovalsRequestIdRoute
  '/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/my-resources/$vmid': typeof LayoutMyResourcesVmidRoute
  '/resources/$vmid': typeof LayoutResourcesVmidRoute
  '/admin': typeof LayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/ai-api': typeof LayoutAiApiRoute
  '/_layout/ai-api-approvals': typeof LayoutAiApiApprovalsRoute
  '/_layout/applications': typeof LayoutApplicationsRoute
  '/_layout/applications-create': typeof LayoutApplicationsCreateRoute
  '/_layout/approvals': typeof LayoutApprovalsRoute
  '/_layout/firewall': typeof LayoutFirewallRoute
  '/_layout/groups': typeof LayoutGroupsRoute
  '/_layout/my-resources': typeof LayoutMyResourcesRoute
  '/_layout/resources': typeof LayoutResourcesRoute
  '/_layout/resources-create': typeof LayoutResourcesCreateRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/audit-logs': typeof LayoutAdminAuditLogsRoute
  '/_layout/admin/configuration': typeof LayoutAdminConfigurationRoute
  '/_layout/admin/gateway': typeof LayoutAdminGatewayRoute
  '/_layout/admin/migration-jobs': typeof LayoutAdminMigrationJobsRoute
  '/_layout/approvals_/$requestId': typeof LayoutApprovalsRequestIdRoute
  '/_layout/groups_/$groupId': typeof LayoutGroupsGroupIdRoute
  '/_layout/my-resources_/$vmid': typeof LayoutMyResourcesVmidRoute
  '/_layout/resources_/$vmid': typeof LayoutResourcesVmidRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/ai-api'
    | '/ai-api-approvals'
    | '/applications'
    | '/applications-create'
    | '/approvals'
    | '/firewall'
    | '/groups'
    | '/my-resources'
    | '/resources'
    | '/resources-create'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/configuration'
    | '/admin/gateway'
    | '/admin/migration-jobs'
    | '/approvals/$requestId'
    | '/groups/$groupId'
    | '/my-resources/$vmid'
    | '/resources/$vmid'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/ai-api'
    | '/ai-api-approvals'
    | '/applications'
    | '/applications-create'
    | '/approvals'
    | '/firewall'
    | '/groups'
    | '/my-resources'
    | '/resources'
    | '/resources-create'
    | '/settings'
    | '/'
    | '/admin/audit-logs'
    | '/admin/configuration'
    | '/admin/gateway'
    | '/admin/migration-jobs'
    | '/approvals/$requestId'
    | '/groups/$groupId'
    | '/my-resources/$vmid'
    | '/resources/$vmid'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/ai-api'
    | '/_layout/ai-api-approvals'
    | '/_layout/applications'
    | '/_layout/applications-create'
    | '/_layout/approvals'
    | '/_layout/firewall'
    | '/_layout/groups'
    | '/_layout/my-resources'
    | '/_layout/resources'
    | '/_layout/resources-create'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/audit-logs'
    | '/_layout/admin/configuration'
    | '/_layout/admin/gateway'
    | '/_layout/admin/migration-jobs'
    | '/_layout/approvals_/$requestId'
    | '/_layout/groups_/$groupId'
    | '/_layout/my-resources_/$vmid'
    | '/_layout/resources_/$vmid'
    | '/_layout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources-create': {
      id: '/_layout/resources-create'
      path: '/resources-create'
      fullPath: '/resources-create'
      preLoaderRoute: typeof LayoutResourcesCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources': {
      id: '/_layout/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-resources': {
      id: '/_layout/my-resources'
      path: '/my-resources'
      fullPath: '/my-resources'
      preLoaderRoute: typeof LayoutMyResourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/firewall': {
      id: '/_layout/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof LayoutFirewallRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/approvals': {
      id: '/_layout/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof LayoutApprovalsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications-create': {
      id: '/_layout/applications-create'
      path: '/applications-create'
      fullPath: '/applications-create'
      preLoaderRoute: typeof LayoutApplicationsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications': {
      id: '/_layout/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof LayoutApplicationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ai-api-approvals': {
      id: '/_layout/ai-api-approvals'
      path: '/ai-api-approvals'
      fullPath: '/ai-api-approvals'
      preLoaderRoute: typeof LayoutAiApiApprovalsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ai-api': {
      id: '/_layout/ai-api'
      path: '/ai-api'
      fullPath: '/ai-api'
      preLoaderRoute: typeof LayoutAiApiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/resources_/$vmid': {
      id: '/_layout/resources_/$vmid'
      path: '/resources/$vmid'
      fullPath: '/resources/$vmid'
      preLoaderRoute: typeof LayoutResourcesVmidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-resources_/$vmid': {
      id: '/_layout/my-resources_/$vmid'
      path: '/my-resources/$vmid'
      fullPath: '/my-resources/$vmid'
      preLoaderRoute: typeof LayoutMyResourcesVmidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups_/$groupId': {
      id: '/_layout/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof LayoutGroupsGroupIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/approvals_/$requestId': {
      id: '/_layout/approvals_/$requestId'
      path: '/approvals/$requestId'
      fullPath: '/approvals/$requestId'
      preLoaderRoute: typeof LayoutApprovalsRequestIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/migration-jobs': {
      id: '/_layout/admin/migration-jobs'
      path: '/migration-jobs'
      fullPath: '/admin/migration-jobs'
      preLoaderRoute: typeof LayoutAdminMigrationJobsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/gateway': {
      id: '/_layout/admin/gateway'
      path: '/gateway'
      fullPath: '/admin/gateway'
      preLoaderRoute: typeof LayoutAdminGatewayRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/configuration': {
      id: '/_layout/admin/configuration'
      path: '/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof LayoutAdminConfigurationRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/audit-logs': {
      id: '/_layout/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof LayoutAdminAuditLogsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAuditLogsRoute: typeof LayoutAdminAuditLogsRoute
  LayoutAdminConfigurationRoute: typeof LayoutAdminConfigurationRoute
  LayoutAdminGatewayRoute: typeof LayoutAdminGatewayRoute
  LayoutAdminMigrationJobsRoute: typeof LayoutAdminMigrationJobsRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAuditLogsRoute: LayoutAdminAuditLogsRoute,
  LayoutAdminConfigurationRoute: LayoutAdminConfigurationRoute,
  LayoutAdminGatewayRoute: LayoutAdminGatewayRoute,
  LayoutAdminMigrationJobsRoute: LayoutAdminMigrationJobsRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAiApiRoute: typeof LayoutAiApiRoute
  LayoutAiApiApprovalsRoute: typeof LayoutAiApiApprovalsRoute
  LayoutApplicationsRoute: typeof LayoutApplicationsRoute
  LayoutApplicationsCreateRoute: typeof LayoutApplicationsCreateRoute
  LayoutApprovalsRoute: typeof LayoutApprovalsRoute
  LayoutFirewallRoute: typeof LayoutFirewallRoute
  LayoutGroupsRoute: typeof LayoutGroupsRoute
  LayoutMyResourcesRoute: typeof LayoutMyResourcesRoute
  LayoutResourcesRoute: typeof LayoutResourcesRoute
  LayoutResourcesCreateRoute: typeof LayoutResourcesCreateRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutApprovalsRequestIdRoute: typeof LayoutApprovalsRequestIdRoute
  LayoutGroupsGroupIdRoute: typeof LayoutGroupsGroupIdRoute
  LayoutMyResourcesVmidRoute: typeof LayoutMyResourcesVmidRoute
  LayoutResourcesVmidRoute: typeof LayoutResourcesVmidRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAiApiRoute: LayoutAiApiRoute,
  LayoutAiApiApprovalsRoute: LayoutAiApiApprovalsRoute,
  LayoutApplicationsRoute: LayoutApplicationsRoute,
  LayoutApplicationsCreateRoute: LayoutApplicationsCreateRoute,
  LayoutApprovalsRoute: LayoutApprovalsRoute,
  LayoutFirewallRoute: LayoutFirewallRoute,
  LayoutGroupsRoute: LayoutGroupsRoute,
  LayoutMyResourcesRoute: LayoutMyResourcesRoute,
  LayoutResourcesRoute: LayoutResourcesRoute,
  LayoutResourcesCreateRoute: LayoutResourcesCreateRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutApprovalsRequestIdRoute: LayoutApprovalsRequestIdRoute,
  LayoutGroupsGroupIdRoute: LayoutGroupsGroupIdRoute,
  LayoutMyResourcesVmidRoute: LayoutMyResourcesVmidRoute,
  LayoutResourcesVmidRoute: LayoutResourcesVmidRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
